// <auto-generated />
using System;
using DAL.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(EntitiesCore))]
    [Migration("20190211020314_LMS")]
    partial class LMS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("DAL.Entities.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("celular");

                    b.Property<string>("email");

                    b.Property<string>("foto");

                    b.Property<int>("idUsuario");

                    b.Property<string>("nome");

                    b.Property<string>("ra");

                    b.HasKey("id");

                    b.HasIndex("celular")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idUsuario");

                    b.ToTable("tb_aluno");
                });

            modelBuilder.Entity("DAL.Entities.Coordenador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("celular");

                    b.Property<string>("email");

                    b.Property<int>("idUsuario");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.HasIndex("celular")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idUsuario");

                    b.ToTable("tb_coordenador");
                });

            modelBuilder.Entity("DAL.Entities.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("apelido");

                    b.Property<string>("celular");

                    b.Property<string>("email");

                    b.Property<int>("idUsuario");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.HasIndex("celular")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idUsuario");

                    b.ToTable("tb_professor");
                });

            modelBuilder.Entity("DAL.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dtExpiracao");

                    b.Property<string>("login");

                    b.Property<string>("senha");

                    b.HasKey("id");

                    b.HasIndex("login")
                        .IsUnique();

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("DAL.Entities.Aluno", b =>
                {
                    b.HasOne("DAL.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DAL.Entities.Coordenador", b =>
                {
                    b.HasOne("DAL.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DAL.Entities.Professor", b =>
                {
                    b.HasOne("DAL.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
