// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entities.core;

namespace entities.Migrations
{
    [DbContext(typeof(EntitiesCore))]
    [Migration("20190211002051_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("entities.core.Entities.Classroom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("desc");

                    b.HasKey("id");

                    b.ToTable("tb_classroom");
                });

            modelBuilder.Entity("entities.core.Entities.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("birthday");

                    b.Property<int?>("idClassroom");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("idClassroom");

                    b.ToTable("tb_person");
                });

            modelBuilder.Entity("entities.core.Entities.Person", b =>
                {
                    b.HasOne("entities.core.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("idClassroom")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
